### ISSUE TITLE
My room disappears

### ISSUE THREAD

**Issue by GUEVARA1962** [Mezeporta/Erupe#10]
There is a problem that my room is lost under the following conditions.

・When entering a room after a world move.
・When I returned from quest and entered the room.
![mhf_20220731_121729_191](https://user-images.githubusercontent.com/103841815/182009564-7cb7ae93-0cd2-4607-8312-649797cbaeb3.jpg)
.

**Comment by GUEVARA1962** [comment]
> There is a problem that my room is lost under the following conditions.
> 
> ・When entering a room after a world move. ・When I returned from quest and entered the room.[mhf_20220731_121729_191](https://user-images.githubusercontent.com/103841815/182009564-7cb7ae93-0cd2-4607-8312-649797cbaeb3.jpg) .

**Comment by sekaiwish** [comment]
This happens when the furniture data gets saved as junk (normal = 0x0000 to 0x0006, junk = 0xFFFF), would have to implement something to check if the furniture is with the 'valid' range. Though what would we do if the furniture is invalid? The player would likely lose all their purchased house themes if we reset it.

**Comment by GUEVARA1962** [comment]
Thx

If you encounter this glitch

　　Go to the bookshelf -> re-select the furniture

the room will appear and the glitch does not seem to have occurred since then.

**Comment by GUEVARA1962** [comment]
Thx

To deal with this glitch, you can

　　Go to the bookshelf -> re-select the furniture

the room will appear and the glitch does not seem to have occurred since then.
